import * as path from "path";
import * as vscode from "vscode";
import { StoryState, getLastCommit, getStoryState, saveStoryState, CommitData } from "./git";
import { generateChapter } from "./generator";
import { maybeSummarize } from "./summarizer";
import { openStoryPanel } from "./storyPanel";
import { showCharacterSheet } from "./characterSheet";
import { requireWorkspaceRoot, getNoirConfig } from "./utils";
import { LLMCaller, makeAnthropicCaller } from "./api";
import { runOnboarding } from "./onboarding";

const SECRET_KEY = "noirCommits.anthropicApiKey";

async function setApiKey(context: vscode.ExtensionContext) {
  const input = await vscode.window.showInputBox({
    title: "Noir Commits: Set Anthropic API Key",
    prompt: "Paste your Anthropic API key. It will be stored encrypted in the OS keychain.",
    password: true,
    ignoreFocusOut: true,
    validateInput: (v) => (v.trim().startsWith("sk-ant-") ? null : "Key should start with sk-ant-"),
  });

  if (!input) {
    return;
  }

  await context.secrets.store(SECRET_KEY, input.trim());
  vscode.window.showInformationMessage("Noir Commits: API key saved securely.");
}

async function setDetectiveName() {
  const current = getNoirConfig().detectiveName;
  const input = await vscode.window.showInputBox({
    title: "Noir Commits: Set Detective Name",
    prompt: "Your alias in the story. Your real git author name is never sent to any AI provider.",
    value: current,
    placeHolder: "e.g. Marlowe, Noir, or leave blank to let the AI choose",
    ignoreFocusOut: true,
  });
  if (input === undefined) {
    return;
  }
  const cfg = vscode.workspace.getConfiguration("noirCommits");
  await cfg.update("detectiveName", input.trim(), vscode.ConfigurationTarget.Global);
  vscode.window.showInformationMessage(
    input.trim()
      ? `Noir Commits: Detective name set to "${input.trim()}".`
      : "Noir Commits: Detective name cleared — the AI will choose one."
  );
}

async function deleteApiKey(context: vscode.ExtensionContext) {
  await context.secrets.delete(SECRET_KEY);
  vscode.window.showInformationMessage("Noir Commits: API key removed.");
}

function tokenToSignal(token: vscode.CancellationToken): AbortSignal {
  const controller = new AbortController();
  if (token.isCancellationRequested) {
    controller.abort();
  } else {
    token.onCancellationRequested(() => controller.abort());
  }
  return controller.signal;
}

function makeAnthropicCallerFromKey(key: string, token?: vscode.CancellationToken): LLMCaller {
  return makeAnthropicCaller(key, getNoirConfig().model, token ? tokenToSignal(token) : undefined);
}

async function resolveCaller(
  context: vscode.ExtensionContext,
  token?: vscode.CancellationToken
): Promise<LLMCaller | undefined> {
  const key = await context.secrets.get(SECRET_KEY);
  if (key) {
    return makeAnthropicCallerFromKey(key, token);
  }

  await setApiKey(context);
  const newKey = await context.secrets.get(SECRET_KEY);
  return newKey ? makeAnthropicCallerFromKey(newKey, token) : undefined;
}

const AI_DISCLOSURE_HEADER =
  `<!-- This story is AI-generated by Noir Commits (https://github.com/girlandred/NoirGenerator). ` +
  `Commit messages and diffs from this repository were used as story prompts. ` +
  `No author names were shared with any AI provider. -->\n\n`;

async function appendToStoryFile(
  root: string,
  commit: CommitData,
  chapterCount: number,
  chapter: string
): Promise<void> {
  const storyUri = vscode.Uri.file(path.join(root, "story.md"));
  const openDoc = vscode.workspace.textDocuments.find(
    (d) => d.uri.fsPath === storyUri.fsPath && d.isDirty
  );
  if (openDoc) {
    await openDoc.save();
  }

  let existing = "";
  try {
    existing = new TextDecoder().decode(await vscode.workspace.fs.readFile(storyUri));
  } catch {
    // file doesn't exist yet
  }

  const isNew = !existing;
  const header = `*Chapter ${chapterCount} — ${commit.date}*\n\n`;
  const separator = existing ? "\n\n---\n\n" : "";
  const prefix = isNew ? AI_DISCLOSURE_HEADER : "";
  await vscode.workspace.fs.writeFile(
    storyUri,
    new TextEncoder().encode(prefix + existing + separator + header + chapter)
  );
}

const writesInProgress = new Set<string>();

async function runNoirWrite(context: vscode.ExtensionContext, root?: string) {
  if (!root) {
    root = requireWorkspaceRoot();
    if (!root) {
      return;
    }
  }

  if (writesInProgress.has(root)) {
    return;
  }
  writesInProgress.add(root);

  try {
    await vscode.window.withProgress(
      { location: vscode.ProgressLocation.Notification, title: "Noir Commits", cancellable: true },
      async (progress, token) => {
        const caller = await resolveCaller(context, token);
        if (!caller || token.isCancellationRequested) {
          return;
        }

        progress.report({ message: "Reading the last commit…" });
        const [commit, state] = await Promise.all([getLastCommit(root), getStoryState(root)]);

        if (!commit) {
          vscode.window.showErrorMessage("Noir Commits: Could not read the last commit.");
          return;
        }
        if (state.lastProcessedHash === commit.hash) {
          vscode.window.showInformationMessage("Noir Commits: This commit already has a chapter.");
          return;
        }
        if (token.isCancellationRequested) {
          return;
        }

        try {
          progress.report({ message: "Writing the next chapter (AI-generated)…" });
          const { detectiveName } = getNoirConfig();
          const { chapter, characters, openThreads } = await generateChapter(
            commit,
            state,
            caller,
            detectiveName || undefined
          );

          if (token.isCancellationRequested) {
            return;
          }

          const newChapters = [
            ...state.chapters,
            { hash: commit.hash, chapter, date: commit.date },
          ];
          const summary = await maybeSummarize({ ...state, chapters: newChapters }, caller);

          const updatedState: StoryState = {
            ...state,
            chapters: newChapters,
            lastProcessedHash: commit.hash,
            chapterCount: state.chapterCount + 1,
            previousSummary: summary,
            characters,
            openThreads,
          };

          await Promise.all([
            saveStoryState(root, updatedState),
            appendToStoryFile(root, commit, updatedState.chapterCount, chapter),
          ]);

          openStoryPanel(context, root);
          vscode.window.showInformationMessage(
            `Noir Commits: Chapter written for "${commit.message}"`
          );
        } catch (err) {
          if (token.isCancellationRequested) {
            return;
          }
          const msg = err instanceof Error ? err.message : "An unexpected error occurred.";
          vscode.window.showErrorMessage(`Noir Commits: ${msg}`);
        }
      }
    );
  } finally {
    writesInProgress.delete(root);
  }
}

async function skipCommit() {
  const root = requireWorkspaceRoot();
  if (!root) {
    return;
  }

  const commit = await getLastCommit(root);
  if (!commit) {
    vscode.window.showErrorMessage("Noir Commits: Could not read the last commit.");
    return;
  }

  const state = await getStoryState(root);
  await saveStoryState(root, { ...state, lastProcessedHash: commit.hash });
  vscode.window.showInformationMessage(`Noir Commits: Skipped "${commit.message}".`);
}

export function activate(context: vscode.ExtensionContext) {
  const watchers = new Map<string, vscode.FileSystemWatcher>();

  function watchFolder(folder: vscode.WorkspaceFolder) {
    const root = folder.uri.fsPath;
    if (watchers.has(root)) {
      return;
    }
    const w = vscode.workspace.createFileSystemWatcher(
      new vscode.RelativePattern(folder, ".git/COMMIT_EDITMSG")
    );
    w.onDidChange(() => runNoirWrite(context, root), null, context.subscriptions);
    w.onDidCreate(() => runNoirWrite(context, root), null, context.subscriptions);
    watchers.set(root, w);
  }

  function unwatchFolder(root: string) {
    watchers.get(root)?.dispose();
    watchers.delete(root);
  }

  function startWatchers() {
    for (const folder of vscode.workspace.workspaceFolders ?? []) {
      watchFolder(folder);
    }
  }

  function stopWatchers() {
    for (const root of watchers.keys()) {
      unwatchFolder(root);
    }
  }

  async function toggleAutoTrigger() {
    const { autoTrigger } = getNoirConfig();
    const cfg = vscode.workspace.getConfiguration("noirCommits");
    await cfg.update("autoTrigger", !autoTrigger, vscode.ConfigurationTarget.Global);
    vscode.window.showInformationMessage(
      `Noir Commits: Auto-generate after commit ${!autoTrigger ? "enabled" : "disabled"}.`
    );
  }

  if (getNoirConfig().autoTrigger) {
    startWatchers();
  }

  const cfg = vscode.workspace.getConfiguration("noirCommits");
  if (cfg.get("provider") !== undefined) {
    cfg.update("provider", undefined, vscode.ConfigurationTarget.Global);
  }

  runOnboarding(context);

  context.subscriptions.push(
    vscode.commands.registerCommand("noirCommits.writeChapter", () => runNoirWrite(context)),
    vscode.commands.registerCommand("noirCommits.skipCommit", () => skipCommit()),
    vscode.commands.registerCommand("noirCommits.setApiKey", () => setApiKey(context)),
    vscode.commands.registerCommand("noirCommits.deleteApiKey", () => deleteApiKey(context)),
    vscode.commands.registerCommand("noirCommits.toggleAutoTrigger", toggleAutoTrigger),
    vscode.commands.registerCommand("noirCommits.openStoryPanel", () => {
      const root = requireWorkspaceRoot();
      if (root) {
        openStoryPanel(context, root);
      }
    }),
    vscode.commands.registerCommand("noirCommits.setDetectiveName", () => setDetectiveName()),
    vscode.commands.registerCommand("noirCommits.showCharacters", () => {
      const root = requireWorkspaceRoot();
      if (root) {
        showCharacterSheet(context, root);
      }
    }),
    vscode.workspace.onDidChangeConfiguration((e) => {
      if (!e.affectsConfiguration("noirCommits.autoTrigger")) {
        return;
      }
      if (getNoirConfig().autoTrigger) {
        startWatchers();
      } else {
        stopWatchers();
      }
    }),
    vscode.workspace.onDidChangeWorkspaceFolders((e) => {
      if (!getNoirConfig().autoTrigger) {
        return;
      }
      for (const folder of e.added) {
        watchFolder(folder);
      }
      for (const folder of e.removed) {
        unwatchFolder(folder.uri.fsPath);
      }
    }),
    { dispose: stopWatchers }
  );

  return { globalState: context.globalState };
}

export function deactivate() {}
